set(RENDERER_DEPENDENCY_CACHE_DIR "${PROJECT_SOURCE_DIR}/thirdparty/cache" CACHE PATH "Downloaded dependency cache")
set(VC_LTL_Root "${RENDERER_DEPENDENCY_CACHE_DIR}/VC-LTL-5.3.1" CACHE PATH "VC-LTL binary package root")
set(METAHOOK_SOURCE_PATH "$ENV{METAHOOK_SOURCE_PATH}" CACHE PATH "MetaHook source tree; empty fetches the pinned SDK")
set(FREEIMAGE_SOURCE_PATH "$ENV{FREEIMAGE_SOURCE_PATH}" CACHE PATH "FreeImage source tree with CMakeLists.txt and Source/FreeImage.h")
set(CAPSTONE_INCLUDE_DIRS "$ENV{CAPSTONE_INCLUDE_DIRS}" CACHE STRING "External Capstone include directories; empty uses the pinned submodule")
set(SDL2_INCLUDE_DIRS "$ENV{SDL2_INCLUDE_DIRS}" CACHE STRING "External include directories containing SDL2/SDL_video.h (required)")
set(SDL3_INCLUDE_DIRS "$ENV{SDL3_INCLUDE_DIRS}" CACHE STRING "External include directories containing SDL3/SDL.h (optional)")

function(renderer_init_submodule name)
    if(NOT EXISTS "${PROJECT_SOURCE_DIR}/thirdparty/${name}/.git")
        find_package(Git REQUIRED)
        execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${PROJECT_SOURCE_DIR}"
            submodule update --init -- "thirdparty/${name}" RESULT_VARIABLE result)
        if(NOT result EQUAL 0)
            message(FATAL_ERROR "Cannot initialize thirdparty/${name}: ${result}")
        endif()
    endif()
endfunction()

function(renderer_prepare_dependencies)
    # Validate explicit paths before doing any downloads. External trees are read-only inputs.
    if(NOT SDL2_INCLUDE_DIRS)
        message(FATAL_ERROR "Set SDL2_INCLUDE_DIRS to the include directory provided by MetaHook's SDL build (containing SDL2/SDL_video.h). Renderer does not fetch or build SDL.")
    endif()
    foreach(version 2 3)
        set(sdl_includes)
        set(sdl_header_found FALSE)
        if(version EQUAL 2)
            set(sdl_header SDL2/SDL_video.h)
        else()
            set(sdl_header SDL3/SDL.h)
        endif()
        foreach(directory IN LISTS SDL${version}_INCLUDE_DIRS)
            get_filename_component(directory "${directory}" ABSOLUTE BASE_DIR "${PROJECT_SOURCE_DIR}")
            if(NOT IS_DIRECTORY "${directory}")
                message(FATAL_ERROR "SDL${version}_INCLUDE_DIRS directory does not exist: ${directory}")
            endif()
            if(EXISTS "${directory}/${sdl_header}")
                set(sdl_header_found TRUE)
            endif()
            list(APPEND sdl_includes "${directory}")
        endforeach()
        if(SDL${version}_INCLUDE_DIRS AND NOT sdl_header_found)
            message(FATAL_ERROR "SDL${version}_INCLUDE_DIRS must provide ${sdl_header}")
        endif()
        set(RENDERER_SDL${version}_INCLUDE_DIRS "${sdl_includes}" PARENT_SCOPE)
    endforeach()
    set(capstone_includes)
    set(capstone_header_found FALSE)
    foreach(directory IN LISTS CAPSTONE_INCLUDE_DIRS)
        get_filename_component(directory "${directory}" ABSOLUTE BASE_DIR "${PROJECT_SOURCE_DIR}")
        if(NOT IS_DIRECTORY "${directory}")
            message(FATAL_ERROR "CAPSTONE_INCLUDE_DIRS directory does not exist: ${directory}")
        endif()
        # Accept either include/ or include/capstone/ from a Capstone source/install tree.
        if(EXISTS "${directory}/capstone.h")
            set(capstone_header_found TRUE)
        elseif(EXISTS "${directory}/capstone/capstone.h")
            string(APPEND directory "/capstone")
            set(capstone_header_found TRUE)
        endif()
        list(APPEND capstone_includes "${directory}")
    endforeach()
    if(CAPSTONE_INCLUDE_DIRS AND NOT capstone_header_found)
        message(FATAL_ERROR "CAPSTONE_INCLUDE_DIRS must provide capstone.h or capstone/capstone.h")
    endif()
    if(DEFINED CAPSTONE_LIBRARY_DIRS)
        message(STATUS "CAPSTONE_LIBRARY_DIRS is ignored: Renderer uses Capstone headers through the MetaHook API and does not link Capstone.")
    endif()
    if(METAHOOK_SOURCE_PATH)
        get_filename_component(metahook_source "${METAHOOK_SOURCE_PATH}" ABSOLUTE BASE_DIR "${PROJECT_SOURCE_DIR}")
    else()
        include(FetchContent)
        FetchContent_Declare(renderer_metahook
            GIT_REPOSITORY https://github.com/MetaHookSv/MetaHook
            GIT_TAG 4d23b6fecd79dc949aabc2e145480cd1328d4a35
            GIT_SUBMODULES ""
            GIT_SUBMODULES_RECURSE FALSE
            # This SDK directory has no CMakeLists.txt: populate without building the launcher.
            SOURCE_SUBDIR include
        )
        FetchContent_MakeAvailable(renderer_metahook)
        set(metahook_source "${renderer_metahook_SOURCE_DIR}")
    endif()
    foreach(required include/metahook.h include/HLSDK/common/interface.cpp include/SourceSDK/filesystem.cpp include/vgui_controls/Panel.cpp)
        if(NOT EXISTS "${metahook_source}/${required}")
            message(FATAL_ERROR "METAHOOK_SOURCE_PATH is missing ${required}: ${metahook_source}")
        endif()
    endforeach()
    set(METAHOOK_SOURCE_PATH "${metahook_source}" PARENT_SCOPE)
    message(STATUS "METAHOOK_SOURCE_PATH: ${metahook_source}")

    if(FREEIMAGE_SOURCE_PATH)
        get_filename_component(source "${FREEIMAGE_SOURCE_PATH}" ABSOLUTE BASE_DIR "${PROJECT_SOURCE_DIR}")
    else()
        renderer_init_submodule(FreeImage_clone)
        set(source "${PROJECT_SOURCE_DIR}/thirdparty/FreeImage_clone")
    endif()
    if(NOT EXISTS "${source}/CMakeLists.txt" OR NOT EXISTS "${source}/Source/FreeImage.h")
        message(FATAL_ERROR "FREEIMAGE_SOURCE_PATH must contain CMakeLists.txt and Source/FreeImage.h: ${source}")
    endif()
    set(FREEIMAGE_SOURCE_PATH "${source}" PARENT_SCOPE)
    message(STATUS "FREEIMAGE_SOURCE_PATH: ${source}")
    if(NOT CAPSTONE_INCLUDE_DIRS)
        renderer_init_submodule(capstone_fork)
        set(capstone_includes "${PROJECT_SOURCE_DIR}/thirdparty/capstone_fork/include/capstone")
    endif()
    set(RENDERER_CAPSTONE_INCLUDE_DIRS "${capstone_includes}" PARENT_SCOPE)
    message(STATUS "Capstone headers: ${capstone_includes}")
    foreach(module glew_fork ScopeExit tinyobjloader)
        renderer_init_submodule(${module})
    endforeach()
    include("${CMAKE_CURRENT_FUNCTION_LIST_DIR}/VCLTL.cmake")
    renderer_prepare_vcltl()
endfunction()
